#!/usr/bin/env bash

TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"` \
&& curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/user-data
#!/bin/bash
yum update -y
service httpd start
chkconfig httpd on



# set -e
# set -o pipefail

# # get Splunk PW from secrets manager:
# SELF_AZ=$(TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600") \
# && curl -s -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/placement/availability-zone/)
# AWS_REGION=$(echo ${SELF_AZ} | sed 's/[a-z]$//')

# SPLUNK_PASSWORD=$(aws secretsmanager get-secret-value --secret-id splunk_password --query 'SecretString' --output text --region ${AWS_REGION})

# # Change default password
# cat <<EOF > /opt/splunk/etc/system/local/user-seed.conf
# [user_info]
# USERNAME = admin
# PASSWORD = ${SPLUNK_PASSWORD}
# EOF

# /opt/splunk/bin/splunk enable boot-start -systemd-managed 1 --accept-license -user splunk -group splunk

# # boot-start dumps out a broken systemd file, how cute.
# cat <<EOF > /etc/systemd/system/Splunkd.service
# [Unit]
# Description=Systemd service file for Splunk, generated by 'splunk enable boot-start'
# After=network.target

# [Service]
# User=splunk
# Group=splunk
# Type=simple
# Restart=always
# ExecStart=/opt/splunk/bin/splunk _internal_launch_under_systemd
# LimitNOFILE=65536
# SuccessExitStatus=51 52
# RestartPreventExitStatus=51
# RestartForceExitStatus=52
# Delegate=true
# MemoryLimit=100G
# CPUShares=1024

# [Install]
# WantedBy=multi-user.target
# EOF

# systemctl daemon-reload
# systemctl restart Splunkd
# systemctl enable Splunkd

# /opt/splunk/bin/splunk set deploy-poll sal-s-slpkadm01.corp.svbank.com:8089 -auth "admin:${SPLUNK_PASSWORD}"
# /opt/splunk/bin/splunk set servername $(hostname)
